### ISSUE TITLE
Data Validation for text fields

### ISSUE THREAD

**Issue by Leesteak** [cryptaliagy/Fnord#18]
Ensure email takes emails, and that fields arent't blank and service rate is a double truncated to two digits (or rounded or whatever)

**Comment by Leesteak** [comment]
Additionally, we should have proper error messages for all fields as part of the validation (eg a toast that tells the user what kind of data to input, etc)

**Comment by Leesteak** [comment]
Also, the app crashes if you try to sign in without any accounts

**Comment by NGnius** [comment]
If possible, please write validation in a separate class, or at least a separate (public) method - I'll need to be able to call it when writing test cases

**Comment by cryptaliagy** [comment]
Validation for user creation should be finished

**Comment by cryptaliagy** [comment]
Done
