### ISSUE TITLE
CircleCI Integration

### ISSUE THREAD

**Issue by Leesteak** [cryptaliagy/Fnord#22]
Bonus for this deliverable, but mandatory in delverable 4, so extra points now and saved time later.

**Comment by NGnius** [comment]
Setup but not functioning. If I have time, I'll do some more work to get it running.
![image](https://user-images.githubusercontent.com/19637329/48303805-2edde700-e4dd-11e8-91ca-b10f9d15c9fb.png)

**Comment by NGnius** [comment]
Now passing 
![image](https://user-images.githubusercontent.com/19637329/48305185-26dd7180-e4f4-11e8-93b9-fbbf731622d8.png)
