### ISSUE TITLE
Ratings class and property on ServiceProvider

### ISSUE THREAD

**Issue by cryptaliagy** [cryptaliagy/Fnord#35]
To be discussed at the meeting today, further info posted then

**Comment by Leesteak** [comment]
Rating is associated to service provider and booking, and when a homeowner looks at service provider, they can see the last 5 reviews (stars and texts) and also the total average number of stars

**Comment by cryptaliagy** [comment]
It will be important to also add a property under the ServiceProvider class called "ratedTimes", which will be an int that gets incremented every time someone adds a Rating to the Service Provider, as otherwise the averaging function would improperly calculate it
