### ISSUE TITLE
UML Diagram

### ISSUE THREAD

**Issue by Leesteak** [cryptaliagy/Fnord#5]

**Comment by tmayn062** [comment]
Hey everyone, please feel free to comment and suggest changes or fixes...
First draft of UML pasted into a word document:
[Fnord_UML_Deliverable1.docx](https://github.com/NGnius/FnordProjectSEG2105/files/2498665/Fnord_UML_Deliverable1.docx)
The Umple source to copy and paste when we need to make changes:
[UML_Deliv1.txt](https://github.com/NGnius/FnordProjectSEG2105/files/2498666/UML_Deliv1.txt)
or this URL might work (but I don't have much faith in it): http://cruise.eecs.uottawa.ca/umpleonline/umple.php?model=181021118036
Piazza link to instructor confirming we only need th user hierarchy for deliverable 1: https://piazza.com/class/jloe87804ev5k2?cid=196
